steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - europe-west1-docker.pkg.dev/lamp-visual-misalignment/annotation-tool/app:latest
      - -f
      - annotation-tool/Dockerfile
      - .
images:
  - europe-west1-docker.pkg.dev/lamp-visual-misalignment/annotation-tool/app:latest
