[project]
name = "temporal-misalignment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nobodywho>=1.1.0",
    "matplotlib>=3.9",
    "torch>=2.11.0",
    "transformers>=5.5.4",
    "accelerate>=1.13.0",
    "mlx-vlm>=0.4.4",
    "scikit-image>=0.26.0",
    "tqdm>=4.67.3",
    "torchvision>=0.26.0",
    "imageio-ffmpeg>=0.6.0",
]
