// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AnnotateApiAnnotatePostData, AnnotateApiAnnotatePostErrors, AnnotateApiAnnotatePostResponses, CreateSessionApiSessionPostData, CreateSessionApiSessionPostErrors, CreateSessionApiSessionPostResponses, SessionMetricsApiSessionMetricsPostData, SessionMetricsApiSessionMetricsPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Create Session
 */
export const createSessionApiSessionPost = <ThrowOnError extends boolean = false>(options: Options<CreateSessionApiSessionPostData, ThrowOnError>): RequestResult<CreateSessionApiSessionPostResponses, CreateSessionApiSessionPostErrors, ThrowOnError> => (options.client ?? client).post<CreateSessionApiSessionPostResponses, CreateSessionApiSessionPostErrors, ThrowOnError>({
    url: '/api/session',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Session Metrics
 */
export const sessionMetricsApiSessionMetricsPost = <ThrowOnError extends boolean = false>(options: Options<SessionMetricsApiSessionMetricsPostData, ThrowOnError>): RequestResult<SessionMetricsApiSessionMetricsPostResponses, never, ThrowOnError> => (options.client ?? client).post<SessionMetricsApiSessionMetricsPostResponses, never, ThrowOnError>({
    url: '/api/session/metrics',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Annotate
 */
export const annotateApiAnnotatePost = <ThrowOnError extends boolean = false>(options: Options<AnnotateApiAnnotatePostData, ThrowOnError>): RequestResult<AnnotateApiAnnotatePostResponses, AnnotateApiAnnotatePostErrors, ThrowOnError> => (options.client ?? client).post<AnnotateApiAnnotatePostResponses, AnnotateApiAnnotatePostErrors, ThrowOnError>({
    url: '/api/annotate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
