// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8000' | (string & {});
};

/**
 * AnnotateRequest
 */
export type AnnotateRequest = {
    /**
     * Prolific Pid
     */
    prolific_pid: string;
    /**
     * Dataset
     */
    dataset: string;
    /**
     * Task
     */
    task: string;
    /**
     * Sample Index
     */
    sample_index: number;
    /**
     * Human Answer
     */
    human_answer: boolean | Array<number>;
};

/**
 * AnnotateResponse
 */
export type AnnotateResponse = {
    /**
     * Ok
     */
    ok: boolean;
    /**
     * Annotated
     */
    annotated: number;
    /**
     * Total
     */
    total: number;
    /**
     * Completed
     */
    completed: boolean;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * SampleOut
 */
export type SampleOut = {
    /**
     * Sample Index
     */
    sample_index: number;
    /**
     * Sample Name
     */
    sample_name: string;
    /**
     * N Frames
     */
    n_frames: number;
    /**
     * Frame Urls
     */
    frame_urls: Array<string>;
    /**
     * Scene Description
     */
    scene_description: string | null;
};

/**
 * SessionRequest
 */
export type SessionRequest = {
    /**
     * Prolific Pid
     */
    prolific_pid: string;
    /**
     * Dataset
     */
    dataset: string;
    /**
     * Task
     */
    task: string;
};

/**
 * SessionResponse
 */
export type SessionResponse = {
    /**
     * Prolific Pid
     */
    prolific_pid: string;
    /**
     * Dataset
     */
    dataset: string;
    /**
     * Task
     */
    task: string;
    /**
     * Samples
     */
    samples: Array<SampleOut>;
    /**
     * Instructions Md
     */
    instructions_md: string;
    /**
     * Prolific Completion Url
     */
    prolific_completion_url: string;
    /**
     * Total
     */
    total: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type CreateSessionApiSessionPostData = {
    body: SessionRequest;
    path?: never;
    query?: never;
    url: '/api/session';
};

export type CreateSessionApiSessionPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSessionApiSessionPostError = CreateSessionApiSessionPostErrors[keyof CreateSessionApiSessionPostErrors];

export type CreateSessionApiSessionPostResponses = {
    /**
     * Successful Response
     */
    200: SessionResponse;
};

export type CreateSessionApiSessionPostResponse = CreateSessionApiSessionPostResponses[keyof CreateSessionApiSessionPostResponses];

export type AnnotateApiAnnotatePostData = {
    body: AnnotateRequest;
    path?: never;
    query?: never;
    url: '/api/annotate';
};

export type AnnotateApiAnnotatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnnotateApiAnnotatePostError = AnnotateApiAnnotatePostErrors[keyof AnnotateApiAnnotatePostErrors];

export type AnnotateApiAnnotatePostResponses = {
    /**
     * Successful Response
     */
    200: AnnotateResponse;
};

export type AnnotateApiAnnotatePostResponse = AnnotateApiAnnotatePostResponses[keyof AnnotateApiAnnotatePostResponses];
